# Mandell Limitation Knowledge Base (MPC-003 V2)
# Machine-readable verified limitations with evidence tracking.
# AUTONOMY = NO. This is knowledge, not autonomous modification authority.

LIMITATIONS = [
    {
        "id": "ARGUMENT_LOSS",
        "capability": "English translation",
        "limitation": "Multi-word arguments may lose case; translation lowercases",
        "evidence": "copy A → source='a' (store has 'A')",
        "cause": "translate() uses raw_lower for matching",
        "affected_path": "form/mandell/translate.py",
        "severity": "MEDIUM",
        "workaround": "Use lowercase keys or direct Mandell",
        "status": "KNOWN",
        "last_verified_against": "b4b7af1904415b0765434aaef2c134181a7e8c9f",
        "mitigation": "None yet",
        "resolution": "Preserve case in argument extraction",
    },
    {
        "id": "ENGLISH_UNREACHABLE_OPERATION",
        "capability": "English → Dell",
        "limitation": "Many Dells lack English patterns",
        "evidence": "Calculated at runtime via translate() coverage",
        "cause": "Patterns added incrementally, not systematically",
        "affected_path": "form/mandell/translate.py",
        "severity": "MEDIUM",
        "workaround": "Use direct Mandell syntax",
        "status": "IN_PROGRESS",
        "last_verified_against": "b4b7af1904415b0765434aaef2c134181a7e8c9f",
        "mitigation": "14 Dells now reachable via English",
        "resolution": "Systematic English coverage",
    },
    {
        "id": "CONDITIONAL_SEMANTIC_LOSS",
        "capability": "Safe translation",
        "limitation": "Conditionals on destructive ops → UNKNOWN (safe)",
        "evidence": "'delete X if empty' → UNKNOWN (was: unconditional delete)",
        "cause": "No conditional execution semantics in Mandell",
        "affected_path": "form/mandell/translate.py:SEMANTIC_LOSS_GUARD",
        "severity": "HIGH",
        "workaround": "None; UNKNOWN is correct until conditionals exist",
        "status": "MITIGATED",
        "last_verified_against": "b4b7af1904415b0765434aaef2c134181a7e8c9f",
        "mitigation": "Guard blocks destructive+conditional",
        "resolution": "Implement conditional execution via Branch (60)",
    },
    {
        "id": "LEGACY_ONLY_SIGNATURE",
        "capability": "Typed operations",
        "limitation": "43 Dells lack typed signatures",
        "evidence": "14/57 Dells have signatures (was 6/57)",
        "cause": "Signatures added incrementally via Ω-055/MPC-002/MPC-003",
        "affected_path": "form/mandell/signatures.py",
        "severity": "MEDIUM",
        "workaround": "Use legacy lab syntax",
        "status": "IN_PROGRESS",
        "last_verified_against": "b4b7af1904415b0765434aaef2c134181a7e8c9f",
        "mitigation": "Retrieval + query families typed",
        "resolution": "Continue systematic typing",
    },
    {
        "id": "FLOW_PARTIAL_IMPLEMENTATION",
        "capability": "Flow composition",
        "limitation": "Only 3/9 Flow operators operationally implemented",
        "evidence": ">, :, :: work; >>, >>>, :>, <:, <:>, <<[Delta] defined but not implemented",
        "cause": "Flow contract defined aspirationally",
        "affected_path": "form/mandell/control_runtime.py:FLOW_CONTRACT",
        "severity": "MEDIUM",
        "workaround": "Use > for sequencing, :/:: for args",
        "status": "KNOWN",
        "last_verified_against": "b4b7af1904415b0765434aaef2c134181a7e8c9f",
        "mitigation": "Document which flows work",
        "resolution": "Implement or remove unimplemented flows",
    },
]
