# Mandell Limitation Knowledge Base (MPC-002)
# Machine-readable verified limitations.
# AUTONOMY = NO. This is knowledge, not autonomous modification authority.

LIMITATIONS = [
    {
        "id": "ARGUMENT_LOSS",
        "capability": "English translation",
        "limitation": "Multi-word arguments may lose case; translation lowercases",
        "evidence": "copy A → source='a' (store has 'A')",
        "cause": "translate() uses raw_lower for matching",
        "affected_path": "form/mandell/translate.py",
        "severity": "MEDIUM",
        "workaround": "Use lowercase keys or direct Mandell",
        "status": "KNOWN",
    },
    {
        "id": "ENGLISH_UNREACHABLE_OPERATION",
        "capability": "English → Dell",
        "limitation": "Many Dells lack English patterns",
        "evidence": "51/57 Dells have no English reachability",
        "cause": "Patterns added incrementally, not systematically",
        "affected_path": "form/mandell/translate.py",
        "severity": "MEDIUM",
        "workaround": "Use direct Mandell syntax",
        "status": "KNOWN",
    },
    {
        "id": "AMBIGUOUS_FIND",
        "capability": "Retrieval",
        "limitation": "'find' maps to different Dells by context",
        "evidence": "find X → Dell56; find ideas → UNKNOWN (correct)",
        "cause": "Natural language ambiguity",
        "affected_path": "form/mandell/translate.py:_is_ambiguous_find",
        "severity": "LOW",
        "workaround": "Use specific verbs (get/select/search)",
        "status": "MITIGATED",
    },
    {
        "id": "COMPOSITION_PARSE_FAILURE",
        "capability": "English multi-intent",
        "limitation": "Complex multi-step may not segment correctly",
        "evidence": "Fixed for 'then' patterns; other constructions untested",
        "cause": "Simple regex segmentation",
        "affected_path": "form/mandell/translate.py",
        "severity": "MEDIUM",
        "workaround": "Use explicit Mandell chaining with >",
        "status": "PARTIAL_FIX",
    },
    {
        "id": "CONDITIONAL_SEMANTIC_LOSS",
        "capability": "Safe translation",
        "limitation": "Conditionals on destructive ops → UNKNOWN (safe)",
        "evidence": "'delete X if empty' → UNKNOWN (was: unconditional delete)",
        "cause": "No conditional execution semantics in Mandell",
        "affected_path": "form/mandell/translate.py:SEMANTIC_LOSS_GUARD",
        "severity": "HIGH",
        "workaround": "None; UNKNOWN is correct until conditionals exist",
        "status": "MITIGATED",
    },
    {
        "id": "LEGACY_ONLY_SIGNATURE",
        "capability": "Typed operations",
        "limitation": "51 Dells lack typed signatures",
        "evidence": "Only 10/57 Dells have signatures (was 6/57)",
        "cause": "Signatures added incrementally via Ω-055/MPC-002",
        "affected_path": "form/mandell/signatures.py",
        "severity": "MEDIUM",
        "workaround": "Use legacy lab syntax",
        "status": "IN_PROGRESS",
    },
    {
        "id": "UNKNOWN_OPERATIONAL_SEMANTICS",
        "capability": "Dell completeness",
        "limitation": "Some Dells have unclear operational semantics",
        "evidence": "Dell21: registry says Merge, scope is live-units only",
        "cause": "Historical evolution without semantic audit",
        "affected_path": "Various",
        "severity": "MEDIUM",
        "workaround": "Director decision required",
        "status": "INVESTIGATING",
    },
    {
        "id": "SINGLE_RESULT_CHANNEL_LIMITATION",
        "capability": "Composition",
        "limitation": "Only one last_result channel per execution",
        "evidence": "Multi-value composition requires sequential chaining",
        "cause": "Design: st.last_result is scalar",
        "affected_path": "form/mandell/core_ii_exec.py",
        "severity": "LOW",
        "workaround": "Chain operations sequentially",
        "status": "BY_DESIGN",
    },
]
